name: test_deploy

on:
  # Manual run from the Actions tab or gh CLI
  workflow_dispatch:
    inputs:
      os:
        description: "Comma-separated OS filter (e.g. windows-latest,macos-latest). Leave empty for all."
        required: false
        default: ""
      run_tests:
        description: "Run pytest against each built wheel?"
        type: boolean
        default: true
  # TEMP: Register & allow runs from your branch without merging to default
  push:
    branches: [ feat/add-wheels ]

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        # Both macOS runners to cover Intel (macos-13) and Apple Silicon (macos-latest)
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up host Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v3.1.4
        with:
          output-dir: wheelhouse
        env:
          # Prefer metadata-driven selection via [project] requires-python in pyproject.toml
          #CIBW_PROJECT_REQUIRES_PYTHON: ">=3.11"
          # Optional per-wheel tests
          CIBW_BEFORE_BUILD: "pip install --prefer-binary scipy"
          CIBW_TEST_REQUIRES: ${{ inputs.run_tests && 'pytest' || '' }}
          CIBW_TEST_COMMAND: ${{ inputs.run_tests && 'pytest -q {project}/tests' || '' }}

      - name: Upload wheel artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: wheelhouse/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build sdist
        run: |
          python -m pip install --upgrade pip build
          python -m build --sdist
      - name: Upload sdist artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  collect_artifacts:
    name: Collect all artifacts (no publish)
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    steps:
      - name: Download wheel artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true
      - name: Download sdist
        uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist
      - name: List outputs
        run: ls -lah dist
      - name: Re-upload merged dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*
